services:
  traefik:
    image: traefik:v3.1
    command:
      - --api.dashboard=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/acme.json:/letsencrypt/acme.json
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks: [web]

  frontend_a:
    image: ${FRONTEND_IMAGE}
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # HTTP Router -> Redirect to hhtps
      - "traefik.http.routers.frontA-http.rule=Host(`${FRONTEND_HOST_1}`) || Host(`${FRONTEND_HOST_2}`)"
      - "traefik.http.routers.frontA-http.entrypoints=web"
      - "traefik.http.routers.frontA-http.middlewares=redirect-to-https@docker"
      # HTTPS Router
      - "traefik.http.routers.frontA-https.rule=Host(`${FRONTEND_HOST_1}`) || Host(`${FRONTEND_HOST_2}`)"
      - "traefik.http.routers.frontA-https.entrypoints=websecure"
      - "traefik.http.routers.frontA-https.tls=true"
      - "traefik.http.routers.frontA-https.tls.certresolver=letsencrypt"
      # Port inside the container
      - "traefik.http.services.frontA.loadbalancer.server.port=80"
      # Watchtower
      - com.centurylinklabs.watchtower.enable=true
    depends_on:
      - traefik
    restart: unless-stopped
    networks: [web]
    
  frontend_b:
    image: ${FRONTEND_IMAGE_2}
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # HTTP Router -> Redirect to hhtps
      - "traefik.http.routers.frontB-http.rule=Host(`${FRONTEND_HOST_3}`) || Host(`${FRONTEND_HOST_4}`)"
      - "traefik.http.routers.frontB-http.entrypoints=web"
      - "traefik.http.routers.frontB-http.middlewares=redirect-to-https@docker"
      # HTTPS Router
      - "traefik.http.routers.frontB-https.rule=Host(`${FRONTEND_HOST_3}`) || Host(`${FRONTEND_HOST_4}`)"
      - "traefik.http.routers.frontB-https.entrypoints=websecure"
      - "traefik.http.routers.frontB-https.tls=true"
      - "traefik.http.routers.frontB-https.tls.certresolver=letsencrypt"
      # Port inside the container
      - "traefik.http.services.frontB.loadbalancer.server.port=80"
      # Watchtower
      - com.centurylinklabs.watchtower.enable=true
    depends_on:
      - traefik
    restart: unless-stopped
    networks: [web]
    
  watchtower:
      image: containrrr/watchtower:latest
      restart: unless-stopped
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /root/.docker/:/config:ro
      environment:
        - DOCKER_CONFIG=/config
      command:
        - --label-enable
        - --cleanup
        - --interval=60
        - --rolling-restart

networks:
  web:
    name: playground_web
