services:
  traefik:
    image: traefik:v3.1
    command:
      - --api.dashboard=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/acme.json:/letsencrypt/acme.json
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks: [web]

  frontend_a:
    image: ${FRONTEND_IMAGE}
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.frontA.middlewares=redirect-to-https@docker"
      - "traefik.http.routers.frontA.rule=Host(`${FRONTEND_HOST_1}`) || Host(`${FRONTEND_HOST_2}`)"
      - "traefik.http.routers.frontA.entrypoints=web,websecure"
      - "traefik.http.routers.frontA.tls=true"
      - "traefik.http.routers.frontA.tls.certresolver=letsencrypt"      
      - "traefik.http.services.frontA.loadbalancer.server.port=80"
    depends_on:
      - traefik
    restart: unless-stopped
    networks: [web]
    
  frontend_b:
    image: ${FRONTEND_IMAGE_2}
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.frontB.middlewares=redirect-to-https@docker"
      - "traefik.http.routers.frontB.rule=Host(`${FRONTEND_HOST_3}`) || Host(`${FRONTEND_HOST_4}`)"
      - "traefik.http.routers.frontB.entrypoints=web,websecure"
      - "traefik.http.routers.frontB.tls=true"
      - "traefik.http.routers.frontB.tls.certresolver=letsencrypt"      
      - "traefik.http.services.frontB.loadbalancer.server.port=80"
    depends_on:
      - traefik
    restart: unless-stopped
    networks: [web]

networks:
  web:
    name: playground_web
